Придумайте матрицы, которые обладают следующими свойствами:
a) диагональная, ортогональная, но не единичная(!):
b) верхнетреугольная, ортогональная:
c) нижнетреугольная, ортогональная:
d) матрица, у которой определитель = 1, и все элементы не равны 0:
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

In [2]:
import numpy as np

In [15]:
# a) диагональная, ортогональная, но не единичная(!)
A = np.array([[-1, 0, 0], [0, 1, 0],[0, 0, -1]])
A

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [16]:
# Проверим:
A_t = A.transpose()
A_t

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [17]:
I = A @ A_t
I
# Получается единичная

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
# b) верхнетреугольная, ортогональная
B = np.array([[-1, 0, 0], [0, -1, 0],[0, 0, -1]])
B

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [19]:
# Проверим:
B_t = B.transpose()
B_t

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [20]:
I = B @ B_t
I
# Получается единичная

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
# c) нижнетреугольная, ортогональная
# тоже самое и B
C = np.array([[-1, 0, 0], [0, -1, 0],[0, 0, -1]])
C

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [22]:
# Проверим:
C_t = C.transpose()
I = B @ C_t
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [71]:
# d) матрица, у которой определитель = 1, и все элементы не равны 0
D = np.array([[1/2, 1, -1/2],
              [-1/2, 1, 1],
              [1/2, 1, 1/2]])

In [72]:
D_det = np.linalg.det(D)
D_det

1.0

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
[1, 3]])

print(m)

In [3]:
# Да, забыла часть задания..
m = np.array([[2, 2],
[1, 3]])

print(m)

[[2 2]
 [1 3]]


In [10]:
k, V = np.linalg.eig(m)
print(f'Собственное значение: {k[0]} и соответствующий вектор: {V[0]}')
print(f'Собственное значение: {k[1]} и соответствующий вектор: {V[1]}')

Собственное значение: 1.0 и соответствующий вектор: [-0.89442719 -0.70710678]
Собственное значение: 4.0 и соответствующий вектор: [ 0.4472136  -0.70710678]
